Open-RSC/Core-Framework

server/src/com/rscdaemon/scripting/event/IncreaseXPEvent.java
server/src/com/rscdaemon/scripting/quest/DefaultExperience.java
server/src/org/openrsc/server/entityhandling/defs/extras/AgilityCourseDef.java
server/src/org/openrsc/server/event/FiremakingEvent.java
server/src/org/openrsc/server/event/MiningEvent.java
server/src/org/openrsc/server/event/WoodcutEvent.java
server/src/org/openrsc/server/internal/DefaultFatigueApplicator.java
server/src/org/openrsc/server/internal/FatigueApplicator.java
server/src/org/openrsc/server/internal/NoOpFatigueApplicator.java
server/src/org/openrsc/server/model/AgilityHandler.java
server/src/org/openrsc/server/model/Npc.java
server/src/org/openrsc/server/model/Player.java
server/src/org/openrsc/server/packethandler/InvActionHandler.java
server/src/org/openrsc/server/packethandler/InvUseOnItem.java
server/src/org/openrsc/server/packethandler/InvUseOnObject.java
server/src/org/openrsc/server/packethandler/NpcCommand.java
server/src/org/openrsc/server/packethandler/ObjectAction.java
server/src/org/openrsc/server/packethandler/SpellHandler.java
server/src/org/openrsc/server/packethandler/WallObjectAction.java

Add fatigue enable/disable via config

---

server/src/org/openrsc/server/model/Player.java

Sorry guys, had to inline the method I added again after realising it would apply experience even if a player was fatigued.

Fix bug: Experience would be granted even when player fatigued.

---

server/src/org/openrsc/server/packethandler/InvUseOnObject.java

Issue #166
Changed ID from 286 to 283

[Fix] Pirate's Treasure reward changed

---

server/src/org/openrsc/server/packethandler/InvUseOnObject.java

Iron ore smelting is now a 50% chance at a furnace

---

server/src/org/openrsc/server/packethandler/InvUseOnObject.java

Added cannon ball smithing

---

server/src/org/openrsc/server/packethandler/InvUseOnObject.java

Deleted unnecessary check.
Credits to Tessa

Cannon ball smithing optimization

---

client/src/org/openrsc/client/Group.java
server/src/org/openrsc/server/model/Group.java

Update name color on hover from yellow to white for normal players.

---

client/src/org/openrsc/client/Group.java
client/src/org/openrsc/client/mudclient.java

Fix chat and right-click colours.

---

server/src/org/openrsc/server/packethandler/InvUseOnObject.java

Issue #278
Requires Cook's Assistant in order to be used now.

Fixed Chef's range in lumbridge

---

server/src/org/openrsc/server/model/Inventory.java
server/src/org/openrsc/server/packethandler/InvUseOnObject.java

Issue #270
Also includes Fixed Cook's Range for special occasions

Removed unnecessary drop message

---

server/src/org/openrsc/server/packethandler/ObjectAction.java

The file got reformatted while in my hands - My .vimrc did a number on it and turned tabs into spaces. This was not my intention, but what is done is done. Do a side-by-side comparison on handleMining to see the actual changes. Pretty simple. Tested for all pickaxes.

Fix mining attempt counts (see handleMining for changes).

---

server/src/org/openrsc/server/packethandler/PickupItem.java

You can now pick up items off of objects one square away.

---

server/plugins/com/openrsc/server/plugins/deefault/DoorAction.java

Should help if we need to debug any of these ones (ex: McGrouber's for woodcutting guild..)

Add some comments for doors.

---

client/src/rsc/mudclient.java

Introduced by https://github.com/Open-RSC/Game/pull/703

client: Fix npc/player creation position coordinate

---

server/src/com/openrsc/server/model/entity/player/Player.java

Forces the server to deal with only one packet of a specific type at a time, on a per-player basis. This effectively rate-limits packet processing and reduces likelyhood of packet spam causing exploits.

Change incomingPacket object to LinkedHashMap

---

server/build.xml
server/plugins/com/openrsc/server/plugins/commands/Admins.java
server/src/com/openrsc/server/Server.java
server/src/com/openrsc/server/io/WorldLoader.java
server/src/com/openrsc/server/plugins/Functions.java
server/src/com/openrsc/server/plugins/PluginHandler.java

Needs testing, should run ticks more consistently and warn the user when the server is running too slow.
Garbage collection should also be steadier.

Core: Timing changes with ticks

---

server/plugins/com/openrsc/server/plugins/quests/members/MerlinsCrystal.java

Fix: Merlins Crystal

---

server/plugins/com/openrsc/server/plugins/npcs/karamja/BoatFromKaramja.java

Added missing ObjectID, ship had three parts the middle one was missing. Should be fine now.

Fix: Karamja Boat

---

server/src/com/openrsc/server/model/entity/Entity.java

Disabling unwielding of members items in wilderness

---

Databases/openrsc_game.sql
server/free.conf
server/members.conf
server/src/com/openrsc/server/Constants.java
server/src/com/openrsc/server/model/entity/npc/Npc.java

This adds NPC kill counts with optional NPC kill count messages.

Added NPC kill logging

---

server/plugins/com/openrsc/server/plugins/quests/free/TheRestlessGhost.java

Restless Ghost fixes npc spawns ghost and skeleton

Fix: Restless Ghost

---

server/plugins/com/openrsc/server/plugins/quests/members/PlagueCity.java

Fixes dialogue and adds option to get new magic scroll after the quest is complete

Fix: Plague City (quest)

---

server/src/com/openrsc/server/io/WorldLoader.java
server/src/com/openrsc/server/model/world/region/TileValue.java

horizontalWallVal: int -> byte
overlay: int -> byte
verticalWallVal: int -> byte

TileValue variable type changes.

---

server/plugins/com/openrsc/server/plugins/quests/members/touristtrap/TouristTrap.java

Fixes the part after finishing the quest, you should be able to retrieve the metal key again after the quest .

Fix: Tourist Trap

---

server/plugins/com/openrsc/server/plugins/itemactions/InvAction.java
server/plugins/com/openrsc/server/plugins/npcs/alkharid/ShantayPassNpcs.java

1 in 25 chance to drop the paper.
Also changed a bunch of `if`s into `else if` so the server processes less when a player uses an item in their inventory.

Shantay now drops a Scrumpled piece of paper, and the paper works!

---

server/plugins/com/openrsc/server/plugins/skills/agility/AgilityShortcuts.java

Fixes the ropeswing to give proper exp.

Fix: Grew's Rope Swing (watchtower)

---

server/plugins/com/openrsc/server/plugins/quests/members/Waterfall_Quest.java
server/plugins/com/openrsc/server/plugins/quests/members/grandtree/GrandTree.java

Grand tree (agility level requirements) & Waterfall quest added missing dialogues and object actions

Fix: Grand Tree & Waterfall

---

server/src/com/openrsc/server/net/rsc/handlers/ChatHandler.java
server/src/com/openrsc/server/net/rsc/handlers/FriendHandler.java
server/src/com/openrsc/server/util/rsc/DataConversions.java

Chat now capitalizes properly.

---

scripts/db/remove_klanks.sql
scripts/v1 to v2 conversion process.txt

Added a note to the conversion process text file. Added the script to execute in scripts/db folder. 
Server might need to be off during execution since someone could log out with Klanks after removal and DB would update, causing them to keep the Klanks.

Issue #596 - Klanks Removal Script

---

client/src/orsc/Config.java

This allows the use of a custom cache directory and makes the client a little bit easier to set up with certain IDEs. This has proven very useful to me.

Added custom cache directory and cache versioning

---

server/plugins/com/openrsc/server/plugins/quests/free/DemonSlayer.java
server/plugins/com/openrsc/server/plugins/quests/free/ImpCatcher.java
server/src/com/openrsc/server/plugins/Functions.java

Quest fixes.

---

server/plugins/com/openrsc/server/plugins/commands/Admins.java
server/src/com/openrsc/server/event/custom/HourlyEvent.java

Implement ::holidaydrop <repeatTimes> <itemid> command to spawn a list of items across the world map. You can enter as many item ids as you would like.
Example (halloween masks):
::holidaydrop 2 828 831 832
The above will repeat twice, executing first on the 0th second of the next hour mark.

Holiday Drops Admin Command

---

server/plugins/com/openrsc/server/plugins/misc/GnomeBall.java
server/src/com/openrsc/server/event/rsc/impl/BallProjectileEvent.java
server/src/com/openrsc/server/event/rsc/impl/BenignProjectileEvent.java

Fixes gnome ball throwing

---

server/plugins/com/openrsc/server/plugins/npcs/portsarim/Klarense.java
server/plugins/com/openrsc/server/plugins/npcs/portsarim/PortSarimSailor.java

Wrong teleport location & Klarense had wrong package path

Fix: Sailors & Klarense

---

server/src/com/openrsc/server/net/rsc/handlers/SpellHandler.java

added telegrab block for item 723 in spellhandler

Fix: Ice Arrows (telegrab)

---

server/plugins/com/openrsc/server/plugins/skills/BattlestaffCrafting.java
server/plugins/com/openrsc/server/plugins/skills/Crafting.java

Minor - make a is often "make an" if the next word starts with vowel such as You make an orb or You make an unholy symbol of Zamorak

Fixes in crafting messages

---

server/plugins/com/openrsc/server/plugins/quests/members/TempleOfIkov.java

fix allow other arrows after shooting ice arrows

Fix: Temple Of Ikov ( lesarkus )

---

server/plugins/com/openrsc/server/plugins/itemactions/InvUseOnItem.java

Fixes on crystal key, map pieces, crest fragment. Also hints on attempting to join dragon shield half

Fix mechanics on joining partial items

---

server/plugins/com/openrsc/server/plugins/quests/members/FishingContest.java

Revised a great portion of the quest and behavior, missing primarily some quest menu echo checks/fixes.

Fixes in Fishing Contest quest

---

server/plugins/com/openrsc/server/plugins/npcs/portsarim/BettysMagicEmporium.java

Fix: Betty stocks (magic shop)

---

server/src/com/openrsc/server/net/rsc/LoginPacketHandler.java

allow login while autorestart(countdown timer) is in progress

Fix: Login while AutoRestart

---

server/free.conf
server/members.conf
server/src/com/openrsc/server/Constants.java
server/src/com/openrsc/server/model/world/World.java

This reverts commit 67cf1f7beb1f35227653f8f628da616d63578bdc.

Revert "Fix: AutoRestart"

---

server/plugins/com/openrsc/server/plugins/commands/RegularPlayer.java
server/src/com/openrsc/server/net/rsc/ActionSender.java

Mods and Admins can now use RegularPlayer commands even if it is off by default.
::onlinelist now works but is very plain. Further direction on the desired look of the data in the modal would be appreciated.

RegularPlayer Commands Available To Mods and Admins, ::onlinelist Implemented

---

server/plugins/com/openrsc/server/plugins/quests/free/DemonSlayer.java

Possibly also fixes traiborn whacky conv

Silverlight is not reclaimable post-quest

---

server/plugins/com/openrsc/server/plugins/quests/members/MurderMystery.java

Murder Mystery

---

server/plugins/com/openrsc/server/plugins/npcs/portsarim/NedInShip.java
server/plugins/com/openrsc/server/plugins/quests/free/DragonSlayer.java

Pending primarily mechanics on maze keys

Some fixes dragon slayer

---

server/plugins/com/openrsc/server/plugins/npcs/WeaponMaster.java
server/plugins/com/openrsc/server/plugins/quests/free/ShieldOfArrav.java

added missing dialogue and behavior for WeaponsMaster (37)

Fix: Shield Of Arrav (WeaponMaster)

---

client/src/orsc/PacketHandler.java
client/src/orsc/buffers/RSBufferUtils.java
client/src/orsc/mudclient.java
server/src/com/openrsc/server/net/rsc/ActionSender.java

(And make ground items pull the right type)

Fix up chat handling packets.

---

server/plugins/com/openrsc/server/plugins/npcs/WeaponMaster.java
server/plugins/com/openrsc/server/plugins/npcs/varrock/King.java
server/plugins/com/openrsc/server/plugins/npcs/varrock/ManPhoenix.java
server/plugins/com/openrsc/server/plugins/quests/free/ShieldOfArrav.java
server/plugins/com/openrsc/server/plugins/quests/members/HerosQuest.java

In the database, check the cache value "arrav_gang" and set anyone with the value 0 in that field, to quest stage -2 in the actual quest. UNLESS they are not finished the quest (duh hahaha)

sheild of arrav

---

server/plugins/com/openrsc/server/plugins/deefault/Ladders.java

Fixes paladins blocking ardougne castle stairs

---

server/plugins/com/openrsc/server/plugins/deefault/DoorAction.java

Doormen should no longer shout at you behind closed doors

Fix: Zanaris Doormen

---

server/src/com/openrsc/server/Constants.java

Fix spell max damages

---

server/plugins/com/openrsc/server/plugins/itemactions/Drinkables.java
server/plugins/com/openrsc/server/plugins/skills/Thieving.java
server/src/com/openrsc/server/net/rsc/handlers/SpellHandler.java

Fixes:
Half wine can now be obtainable from drinking wine (though chances are set to be extremely low)
Pickpocket on yanille watchman now are referred watchman, as it should be
A blue wizards hat from legends and coin stacks from Rashiliyas tomb cannot be telegrabbed.

Fixes 2.0.x

---

server/plugins/com/openrsc/server/plugins/itemactions/InvAction.java
server/plugins/com/openrsc/server/plugins/quests/members/PlagueCity.java
server/plugins/com/openrsc/server/plugins/quests/members/watchtower/WatchTowerDialogues.java
server/src/com/openrsc/server/net/rsc/handlers/SpellHandler.java

Fix proper chance to get pearls from oyster

---

server/src/com/openrsc/server/GameStateUpdater.java
server/src/com/openrsc/server/model/WalkingQueue.java
server/src/com/openrsc/server/model/entity/Mob.java

This reverts commit 9a328ed1d30caefe84e43b65aac4d55558f855cd.

Revert "Fix up logout timer and reuse code instead of allowing code duplication for WalkingQueue."

---

server/plugins/com/openrsc/server/plugins/deefault/DoorAction.java
server/plugins/com/openrsc/server/plugins/quests/members/BioHazard.java
server/plugins/com/openrsc/server/plugins/quests/members/Observatory.java
server/plugins/com/openrsc/server/plugins/quests/members/PlagueCity.java
server/plugins/com/openrsc/server/plugins/quests/members/Waterfall_Quest.java

The check on whether the player is allowed to enter the tomb or not may need rework in another commit

Fix up waterfall quest

---

server/plugins/com/openrsc/server/plugins/itemactions/InvUseOnItem.java
server/plugins/com/openrsc/server/plugins/skills/Crafting.java
server/src/com/openrsc/server/util/rsc/Formulae.java

Adding process of making wine and xp when making good wine

---

server/src/com/openrsc/server/model/PathValidation.java
server/src/com/openrsc/server/model/WalkingQueue.java

This is a first attempt. Please make sure you walk around the world a bunch before we throw this to the wolves! :)

Add checks for weird diagonal collisions.

---

server/conf/server/words.list

Shortens word list length to fit on screen

---

client/src/orsc/PacketHandler.java
client/src/orsc/graphics/three/World.java
client/src/orsc/mudclient.java

Adjust some calculations and add an object direction update to attempt to fix broken collisions with wide objects.

Attempted Wide Object Collision Fix

---

server/plugins/com/openrsc/server/plugins/skills/agility/BarbarianAgilityCourse.java

Constraint to level 35 agi the barbarian course

---

client/src/com/openrsc/interfaces/misc/BankInterface.java
client/src/orsc/mudclient.java

Sync on bank interface options on (re)login

---

server/plugins/com/openrsc/server/plugins/npcs/grandtree/Gulluck.java

Fixed Gulluck shop to include mith arrowheard. Verified all other items are correct.

gulluck archer shop mith arrow heads

---

Android/Open RSC Android Client/src/main/java/com/openrsc/interfaces/misc/BankInterface.java
Android/Open RSC Android Client/src/main/java/orsc/mudclient.java
server/plugins/com/openrsc/server/plugins/quests/members/touristtrap/TouristTrap.java
server/plugins/com/openrsc/server/plugins/quests/members/touristtrap/Tourist_Trap_Mechanism.java

Fix: a bit more tourist trap behavior and checks

---

server/plugins/com/openrsc/server/plugins/commands/RegularPlayer.java
server/src/com/openrsc/server/model/entity/player/Player.java
server/src/com/openrsc/server/sql/DatabasePlayerLoader.java
server/src/com/openrsc/server/util/rsc/DataConversions.java

There is one left to fix for a future date. Stripping and saving the location of colour coding in chat strings, to be placed back into the string after doing uppercasing.

Chat: Fix up some missing chat parameters. 

---

server/src/com/openrsc/server/model/entity/Mob.java
server/src/com/openrsc/server/model/entity/player/Trade.java

Also fixes a bug in following where trading would reset the follower and make them stop following.

Initial tweak to following to make it react on a 2 game tick timer.

---

server/plugins/com/openrsc/server/plugins/quests/members/DwarfCannon.java

Fix up a bit more dwarf cannon behavior

---

client/src/orsc/mudclient.java

Comment out login screen repositioning for the time being. A bug was occurring with the viewport that made the viewport wonky if you resized while logged in, and then logged yourself out.

Login Screen Fix. (No reposition for now)

---

server/plugins/com/openrsc/server/plugins/minigames/barcrawl/AlfredGrimhandBarCrawl.java
server/plugins/com/openrsc/server/plugins/npcs/brimhaven/BrimHavenBartender.java
server/plugins/com/openrsc/server/plugins/npcs/falador/Barmaid.java
server/plugins/com/openrsc/server/plugins/npcs/portsarim/Bartender.java
server/plugins/com/openrsc/server/plugins/npcs/seers/SeersBartender.java
server/plugins/com/openrsc/server/plugins/npcs/varrock/Bartender.java
server/plugins/com/openrsc/server/plugins/npcs/varrock/JollyBoarInnBartender.java

Fix mechanics barcrawl miniquest and dialogues

---

Databases/openrsc_game.sql

Corrects overpopulated NPC spawns

---

client/src/orsc/Config.java
client/src/orsc/ORSCApplet.java
client/src/orsc/PacketHandler.java
client/src/orsc/mudclient.java
client/src/orsc/multiclient/ClientPort.java
server/default.conf
server/src/com/openrsc/server/Constants.java
server/src/com/openrsc/server/net/rsc/ActionSender.java

Option to toggle ip at login panel

---

server/plugins/com/openrsc/server/plugins/npcs/ardougne/west/Chadwell.java
server/plugins/com/openrsc/server/plugins/npcs/khazard/FishingTrawlerGeneralStore.java
server/plugins/com/openrsc/server/plugins/npcs/shilo/Fernahei.java

The port khazard and west ardougne general shop should be general, and fernaheis fishing shop in shilo should be particular. Fixes #1617

Fix in some shop mislabeled as non-general, and fernahei fishing shop is particular

---

server/plugins/com/openrsc/server/plugins/itemactions/Eating.java

Adding messages in food that get eaten by parts

---

server/plugins/com/openrsc/server/plugins/quests/free/PiratesTreasure.java

Fix show take banana menu when taking karamja rum

---

server/plugins/com/openrsc/server/plugins/quests/free/VampireSlayer.java
server/src/com/openrsc/server/plugins/Functions.java

Fix on vampire slayer scenery objects and effect of garlic on count draynor

---

server/plugins/com/openrsc/server/plugins/quests/free/DragonSlayer.java
server/plugins/com/openrsc/server/plugins/quests/free/KnightsSword.java
server/plugins/com/openrsc/server/plugins/quests/free/ShieldOfArrav.java
server/plugins/com/openrsc/server/plugins/quests/free/VampireSlayer.java
server/plugins/com/openrsc/server/plugins/quests/members/BioHazard.java
server/plugins/com/openrsc/server/plugins/quests/members/FightArena.java
server/plugins/com/openrsc/server/plugins/quests/members/HazeelCult.java
server/plugins/com/openrsc/server/plugins/quests/members/HerosQuest.java
server/plugins/com/openrsc/server/plugins/quests/members/PlagueCity.java
server/plugins/com/openrsc/server/plugins/quests/members/TribalTotem.java
server/plugins/com/openrsc/server/plugins/quests/members/Waterfall_Quest.java
server/plugins/com/openrsc/server/plugins/quests/members/WitchesHouse.java
server/plugins/com/openrsc/server/plugins/quests/members/digsite/DigsiteObjects.java
server/plugins/com/openrsc/server/plugins/quests/members/grandtree/GrandTree.java

Fix up open/close command on special cupboards and chests

---

server/src/com/openrsc/server/event/rsc/impl/combat/CombatFormula.java

Changed extrapolated range values to make lower-leveled range more forgiving
